dist: trusty
language: node_js
node_js: "8"
sudo: required

matrix:
  fast_finish: true
  include:
    - node_js: "8"
      language: node_js
      env: TEST=WASM
      services: docker

    - language: c++
      env: TEST=CPP
      services: docker

    - python: "3.6"
      language: python
      env: TEST=PYTHON
      cache: pip
      services: docker

    - python: "3.6"
      language: python
      env: TEST=PYTHON_TABLE
      cache: pip
      services: docker

    - language: c++
      env: TEST=CPP_OSX
      os: osx

    - python: "3.6"
      language: python
      env: TEST=DOCS
      cache: pip
      services: docker
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch:
            - master
            - merge_py

  allow_failures:
    - language: c++
      env: TEST=CPP_OSX
      os: osx

env:
  global:
    - EM_USE_GLOBAL_CACHE=1

install:
  - if [ "$TEST" = "CPP_OSX" ]; then brew install yarn; fi
  - yarn
 
script:
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn lint; fi
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn build; fi
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn test --quiet; fi
  - if [ "$TEST" = "CPP" ]; then PSP_DOCKER=1 yarn build_cpp; fi
  - if [ "$TEST" = "CPP" ]; then PSP_DOCKER=1 yarn test_cpp; fi
  - if [ "$TEST" = "PYTHON" ]; then yarn build_python; fi
  - if [ "$TEST" = "PYTHON" ]; then yarn lint_python; fi
  - if [ "$TEST" = "PYTHON" ]; then yarn test_python; fi
  - if [ "$TEST" = "PYTHON_TABLE" ]; then PSP_DOCKER=1 yarn build_python:table; fi
  - if [ "$TEST" = "PYTHON_TABLE" ]; then PSP_DOCKER=1 yarn lint_python:table; fi
  - if [ "$TEST" = "PYTHON_TABLE" ]; then PSP_DOCKER=1 yarn test_python:table; fi
  - if [ "$TEST" = "CPP_OSX" ]; then yarn build_cpp; fi
  - if [ "$TEST" = "CPP_OSX" ]; then yarn test_cpp; fi
  - if [ "$TEST" = "DOCS" ]; then yarn; fi
  - if [ "$TEST" = "DOCS" ]; then yarn autodocs; fi

after_success:
  - if ["$TEST" = "PYTHON" ]; then codecov --token 0f25973b-091f-42fe-a469-95d1c6f7a957; fi
  - if ["$TEST" = "PYTHON" ]; then codecov --token d33ecf96-a51f-43b6-8429-c11f83b961ad; fi
