dist: trusty

language: node_js

node_js:
  - "8"

env:
  global:
    - EM_USE_GLOBAL_CACHE=1

sudo: required

services:
  - docker

install:
  - npm install

jobs:
  include:
    - stage: Build
      script: PSP_DOCKER=1 npm run build
    - stage: Test
      script: PSP_DOCKER=1 npm run test:build
    - stage: Test
      script: PSP_DOCKER=1 npm run test:run
    - stage: Test
      script: npm run test:run_quiet
