dist: trusty

sudo: required

services:
  - docker

env:
  global:
    - EM_USE_GLOBAL_CACHE=1

matrix:
  include:
    - node_js: "8"
      language: node_js
      env: TEST=WASM
    - python: "3.6"
      language: python
      env: TEST=PYTHON
      cache: pip

install:
  - if [ "$TEST" = "WASM" ]; then npm install; fi

script:
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 npm run build; fi
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 npm run test:build; fi
  - if [ "$TEST" = "WASM" ]; then npm run test:run_quiet; fi
  - if [ "$TEST" = "PYTHON" ]; then docker build -f bindings/python/Dockerfile .; fi
